[project]
name = "my-grep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "click>=8.3.3",
]
[project.scripts]
mygrep = "bin.cli:matches_found"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
]
